force-app/main/default/objects/Dreamhouse_Settings__c/fields/WeatherMapApiToken__c.field-meta.xml
<CustomField>
    <fullName>WeatherMapApiToken__c</fullName>
    <label>Weather Map Api Token</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dreamhouse_Settings__c/fields/WeatherMapApiURL__c.field-meta.xml
<CustomField>
    <fullName>WeatherMapApiURL__c</fullName>
    <label>Weather Map Api URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeatherApiPathGenerator.cls
public with sharing class WeatherApiPathGenerator {
   
    private static final String QUESTION_MARK_CHARACTER = '?';
    private static final String AMPERSAND_CHARACTER = '&';
    private static final String CITY_PARAM_NAME = 'q';
    private static final String UNITS_PARAM_NAME = 'units';
    private static final String TOKEN_PARAM_NAME = 'appid';

    private static Dreamhouse_Settings__c customSettings; 
    private static URLBuilder builder;
    
    static{
        customSettings = Dreamhouse_Settings__c.getOrgDefaults();
        builder = new URLBuilder(customSettings.WeatherMapApiURL__c);
    }

    @AuraEnabled(cacheable = true)
    public static String generateEndpointURL() {
        String cityParamValue = 'city_param';
        String unitsParamValue = 'metric';
        String apiToken = customSettings.WeatherMapApiToken__c;
        String weatherApiUrl = builder.appendSeparator(QUESTION_MARK_CHARACTER)
                                .appendParam(CITY_PARAM_NAME, cityParamValue)
                                .appendSeparator(AMPERSAND_CHARACTER)
                                .appendParam(UNITS_PARAM_NAME, unitsParamValue)
                                .appendSeparator(AMPERSAND_CHARACTER)
                                .appendParam(TOKEN_PARAM_NAME, apiToken)
                                .build();
        return weatherApiUrl;
    }
}