force-app/main/default/objects/ContactRemovalHistory__c/ContactRemovalHistory__c.object-meta.xml
<CustomObject>
    <label>Contact Removal History</label>
    <nameField>
        <label>Contact Removal History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Removal Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactRemovalHistory__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <label>Contact Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Contacts.cls
public with sharing class Contacts extends fflib_SObjectDomain {
   
    public Contacts(List<Contact> sObjectList) {
        super(sObjectList);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Contacts(sObjectList);
        }
    }

    public override void onBeforeDelete() {
        List<ContactRemovalHistory__c> historyContacts = new List<ContactRemovalHistory__c>();
        for(Contact deletedContact : (List<Contact>) Records) {
            if(String.isNotBlank(deletedContact.Email)) {
                historyContacts.add(
                    new ContactRemovalHistory__c(Name =  String.valueOf(DateTime.now()),
                     ContactEmail__c = deletedContact.Email));
            }
        }
        insert historyContacts;    
    }
}